/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deltamike.scoa.view.biblioteca;

import deltamike.scoa.controller.biblioteca.BibliotecaController;
import deltamike.scoa.controller.biblioteca.obra.ObraController;
import deltamike.scoa.model.biblioteca.emprestimo.EmprestimoModel;
import deltamike.scoa.model.biblioteca.obra.ObraModel;
import deltamike.scoa.view.Dashboard;
import deltamike.scoa.view.biblioteca.cadastrar.CadastrarArtigoFrame;
import deltamike.scoa.view.biblioteca.cadastrar.CadastrarLivroFrame;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodri
 */
public class BibliotecaDashboard extends javax.swing.JFrame {
    
    /**
     * Creates new form BibliotecaDashboard
     */
    public BibliotecaDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaObras = new javax.swing.JTable();
        AtualizarButton = new javax.swing.JButton();
        checarEmprestimosButton = new javax.swing.JButton();
        PesquisarTextField = new javax.swing.JTextField();
        PesquisarButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastrarLivroItem = new javax.swing.JMenuItem();
        CadastrarJornalItem = new javax.swing.JMenuItem();
        CadastrarFilmeItem = new javax.swing.JMenuItem();
        CadastrarRevistaItem = new javax.swing.JMenuItem();
        CadastrarArtigoItem = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dashboard - Biblioteca");

        TabelaObras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Idioma", "Ano de Publicação", "Tipo", "Palavras chave", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaObras);

        AtualizarButton.setText("Atualizar");
        AtualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarButtonActionPerformed(evt);
            }
        });

        checarEmprestimosButton.setText("Checar emprestimos");
        checarEmprestimosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checarEmprestimosButtonActionPerformed(evt);
            }
        });

        PesquisarButton.setText("Pesquisar");
        PesquisarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("Cadastrar");

        CadastrarLivroItem.setText("Livro");
        CadastrarLivroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarLivroItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarLivroItem);

        CadastrarJornalItem.setText("Jornal");
        CadastrarJornalItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarJornalItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarJornalItem);

        CadastrarFilmeItem.setText("Filme");
        jMenu1.add(CadastrarFilmeItem);

        CadastrarRevistaItem.setText("Revista");
        CadastrarRevistaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarRevistaItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarRevistaItem);

        CadastrarArtigoItem.setText("Artigo");
        CadastrarArtigoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarArtigoItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarArtigoItem);

        jMenuItem6.setText("Manual");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AtualizarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checarEmprestimosButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PesquisarTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PesquisarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtualizarButton)
                    .addComponent(checarEmprestimosButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarJornalItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarJornalItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarJornalItemActionPerformed

    private void CadastrarRevistaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarRevistaItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarRevistaItemActionPerformed

    private void CadastrarLivroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarLivroItemActionPerformed
        // TODO add your handling code here:
        CadastrarLivroFrame cadastrarLivroFrame = new CadastrarLivroFrame();
        
        cadastrarLivroFrame.setVisible(true);
    }//GEN-LAST:event_CadastrarLivroItemActionPerformed

    private void AtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarButtonActionPerformed
        
        if(this.PesquisarTextField.getText().length() > 0){
            this.PesquisarButtonActionPerformed(evt);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) this.TabelaObras.getModel();
        
        ObraController obraController = (ObraController) Dashboard.springAppContext.getBean("obraController");
        List<ObraModel> obras = obraController.getAll().getBody();
        
        model.setRowCount(0);
        
        // a tabela esta na seguinte ordem de colunas
        //Titulo, Idioma, Ano-De-Publicacao, Tipo, palavras-chave
        for(ObraModel obra: obras){
            model.addRow(new Object[]{
                obra.getTitulo(),
                obra.getIdioma(),
                obra.getAnoPublicacao(),
                obra.getTIPO(),
                obra.getPalavrasChave(),
                obra.getId()
            });
        }
        
        
        
        
        
    }//GEN-LAST:event_AtualizarButtonActionPerformed

    private void checarEmprestimosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checarEmprestimosButtonActionPerformed

        DefaultTableModel model = (DefaultTableModel) this.TabelaObras.getModel();
        
        ObraController controller = (ObraController) Dashboard.springAppContext.getBean("obraController");
        
        int id_selection =(Integer) this.TabelaObras.getValueAt(
                this.TabelaObras.getSelectedRow(),
                5
            );
               
        ObraModel obra = (ObraModel) controller.getObraById(id_selection).getBody();
        
        EmprestimosObraFrame emprestimosObraFrame = new EmprestimosObraFrame();
        emprestimosObraFrame.setObra(obra);
        emprestimosObraFrame.setVisible(true);
        
    }//GEN-LAST:event_checarEmprestimosButtonActionPerformed

    private void PesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarButtonActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) this.TabelaObras.getModel();
        
        ObraController obraController = (ObraController) Dashboard.springAppContext.getBean("obraController");
        List<ObraModel> obras = obraController.getByTitulo(this.PesquisarTextField.getText()).getBody();
        
        model.setRowCount(0);
        
        // a tabela esta na seguinte ordem de colunas
        //Titulo, Idioma, Ano-De-Publicacao, Tipo, palavras-chave
        for(ObraModel obra: obras){
            model.addRow(new Object[]{
                obra.getTitulo(),
                obra.getIdioma(),
                obra.getAnoPublicacao(),
                obra.getTIPO(),
                obra.getPalavrasChave(),
                obra.getId()
            });
        }
        
    }//GEN-LAST:event_PesquisarButtonActionPerformed

    private void CadastrarArtigoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarArtigoItemActionPerformed
        // TODO add your handling code here:
        CadastrarArtigoFrame cadastrarArtigoFrame = new CadastrarArtigoFrame();
        cadastrarArtigoFrame.setVisible(true);
        
    }//GEN-LAST:event_CadastrarArtigoItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BibliotecaDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarButton;
    private javax.swing.JMenuItem CadastrarArtigoItem;
    private javax.swing.JMenuItem CadastrarFilmeItem;
    private javax.swing.JMenuItem CadastrarJornalItem;
    private javax.swing.JMenuItem CadastrarLivroItem;
    private javax.swing.JMenuItem CadastrarRevistaItem;
    private javax.swing.JButton PesquisarButton;
    private javax.swing.JTextField PesquisarTextField;
    private javax.swing.JTable TabelaObras;
    private javax.swing.JButton checarEmprestimosButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
