/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deltamike.scoa.view;

import deltamike.scoa.SistemaDeControleAcademicoApplication;
import deltamike.scoa.controller.biblioteca.BibliotecaController;
import deltamike.scoa.controller.biblioteca.obra.ObraController;
import deltamike.scoa.view.biblioteca.BibliotecaDashboard;
import deltamike.scoa.view.financeiro.FinanceiroDashboard;
import deltamike.scoa.view.usuario.UsuarioDashboard;
import javax.swing.JOptionPane;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;

/**
 *
 * @author rodri
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Dashboard() {
        initComponents();
        
        ObraController obraController = (ObraController) springAppContext.getBean("obraController");
        System.out.println(obraController.getAll().getBody());
    }
    
    public static void alert(String s){
        JOptionPane.showMessageDialog(null, s);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AcademicoButton = new javax.swing.JButton();
        AlmoxarifadoButton = new javax.swing.JButton();
        BibliotecaButton = new javax.swing.JButton();
        FinanceiroButton = new javax.swing.JButton();
        UsuarioButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setPreferredSize(new java.awt.Dimension(600, 300));
        setResizable(false);

        AcademicoButton.setText("Acadêmico");
        AcademicoButton.setPreferredSize(new java.awt.Dimension(90, 50));
        AcademicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcademicoButtonActionPerformed(evt);
            }
        });

        AlmoxarifadoButton.setText("Almoxarifado");
        AlmoxarifadoButton.setPreferredSize(new java.awt.Dimension(102, 50));
        AlmoxarifadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmoxarifadoButtonActionPerformed(evt);
            }
        });

        BibliotecaButton.setText("Biblioteca");
        BibliotecaButton.setPreferredSize(new java.awt.Dimension(82, 50));
        BibliotecaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BibliotecaButtonActionPerformed(evt);
            }
        });

        FinanceiroButton.setText("Financeiro");
        FinanceiroButton.setPreferredSize(new java.awt.Dimension(85, 50));
        FinanceiroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinanceiroButtonActionPerformed(evt);
            }
        });

        UsuarioButton.setText("Usuario");
        UsuarioButton.setPreferredSize(new java.awt.Dimension(72, 50));
        UsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(AcademicoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AlmoxarifadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BibliotecaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FinanceiroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcademicoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AlmoxarifadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BibliotecaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FinanceiroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcademicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcademicoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcademicoButtonActionPerformed

    private void AlmoxarifadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmoxarifadoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlmoxarifadoButtonActionPerformed

    private void BibliotecaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BibliotecaButtonActionPerformed
        BibliotecaDashboard bibliotecaDashboard = new BibliotecaDashboard();
        
        bibliotecaDashboard.setVisible(true);
    }//GEN-LAST:event_BibliotecaButtonActionPerformed

    private void UsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioButtonActionPerformed
        // TODO add your handling code here:
        UsuarioDashboard usuarioDashboard = new UsuarioDashboard();
        
        usuarioDashboard.setVisible(true);
    }//GEN-LAST:event_UsuarioButtonActionPerformed

    private void FinanceiroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinanceiroButtonActionPerformed
        // TODO add your handling code here:
        FinanceiroDashboard financeiroDashboard = new FinanceiroDashboard();
        financeiroDashboard.setVisible(true);
    }//GEN-LAST:event_FinanceiroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        springAppContext = SpringApplication.run(SistemaDeControleAcademicoApplication.class, args);
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
     
    public static ConfigurableApplicationContext springAppContext;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcademicoButton;
    private javax.swing.JButton AlmoxarifadoButton;
    private javax.swing.JButton BibliotecaButton;
    private javax.swing.JButton FinanceiroButton;
    private javax.swing.JButton UsuarioButton;
    // End of variables declaration//GEN-END:variables
}
