/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deltamike.scoa.view.academico;

import deltamike.scoa.controller.academico.curso.CursoController;
import deltamike.scoa.model.academico.curso.CursoModel;
import deltamike.scoa.view.Dashboard;
import deltamike.scoa.view.academico.cadastrar.CadastrarCursoFrame;
import deltamike.scoa.view.academico.cadastrar.MatricularAlunoFrame;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodri
 */
public class AcademicoDashboard extends javax.swing.JFrame {
    private List<CursoModel> cursos;
    /**
     * Creates new form AcademicoDashboard
     */
    public AcademicoDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        cursosTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCursos = new javax.swing.JTable();
        atualizarCursosButton = new javax.swing.JButton();
        tab = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cursoMenuItem = new javax.swing.JMenuItem();
        cursoMenu = new javax.swing.JMenu();
        matricularAlunoItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cursosTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cursosTabFocusGained(evt);
            }
        });
        cursosTab.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cursosTabComponentShown(evt);
            }
        });

        tabelaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCursos);

        atualizarCursosButton.setText("Atualizar");
        atualizarCursosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCursosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cursosTabLayout = new javax.swing.GroupLayout(cursosTab);
        cursosTab.setLayout(cursosTabLayout);
        cursosTabLayout.setHorizontalGroup(
            cursosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
            .addGroup(cursosTabLayout.createSequentialGroup()
                .addComponent(atualizarCursosButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cursosTabLayout.setVerticalGroup(
            cursosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarCursosButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cursos", cursosTab);

        tab.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabComponentShown(evt);
            }
        });

        javax.swing.GroupLayout tabLayout = new javax.swing.GroupLayout(tab);
        tab.setLayout(tabLayout);
        tabLayout.setHorizontalGroup(
            tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        tabLayout.setVerticalGroup(
            tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", tab);

        jMenu1.setText("Cadastrar");

        cursoMenuItem.setText("Curso");
        cursoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(cursoMenuItem);

        jMenuBar1.add(jMenu1);

        cursoMenu.setText("Curso");

        matricularAlunoItem.setText("Matricular aluno");
        matricularAlunoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricularAlunoItemActionPerformed(evt);
            }
        });
        cursoMenu.add(matricularAlunoItem);

        jMenuBar1.add(cursoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarCursosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCursosButtonActionPerformed
        // TODO add your handling code here:
        CursoController controller = (CursoController) Dashboard.springAppContext.getBean("cursoController");
        this.cursos = controller.getAll().getBody();
        
        DefaultTableModel model = (DefaultTableModel) this.tabelaCursos.getModel();
        
        //limpando a tabela antes de repopular
        model.setRowCount(0);
        
        for(CursoModel curso : cursos){
            model.addRow(new Object[]{curso.getNome()});
        }
    }//GEN-LAST:event_atualizarCursosButtonActionPerformed

    private void cursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoMenuItemActionPerformed
        // TODO add your handling code here:
        CadastrarCursoFrame cadastrarCursoFrame = new CadastrarCursoFrame();
        cadastrarCursoFrame.setVisible(true);
    }//GEN-LAST:event_cursoMenuItemActionPerformed

    private void cursosTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cursosTabFocusGained
        // TODO add your handling code here:
        System.out.println("tab de cursos mostrada");
    }//GEN-LAST:event_cursosTabFocusGained

    private void cursosTabComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cursosTabComponentShown
        // TODO add your handling code here:
        hideAllDinamicMenus();
        this.cursoMenu.setVisible(true);
    }//GEN-LAST:event_cursosTabComponentShown

    private void tabComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabComponentShown
        // TODO add your handling code here:
        hideAllDinamicMenus();
    }//GEN-LAST:event_tabComponentShown

    private void matricularAlunoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricularAlunoItemActionPerformed
        // TODO add your handling code here:
        if(this.cursos == null){Dashboard.alert("Por favor selecione um curso valido");return;}
        
        DefaultTableModel model = (DefaultTableModel) this.tabelaCursos.getModel();
        
        int selection = this.tabelaCursos.getSelectedRow();
        if(selection == -1){Dashboard.alert("Por favor selecione um curso");return;}
        CursoModel curso = this.cursos.get(selection);
        
        
        MatricularAlunoFrame matricularAlunoFrame = new MatricularAlunoFrame();
        matricularAlunoFrame.setCurso(curso);
        matricularAlunoFrame.setVisible(true);
    }//GEN-LAST:event_matricularAlunoItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcademicoDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcademicoDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcademicoDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcademicoDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcademicoDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarCursosButton;
    private javax.swing.JMenu cursoMenu;
    private javax.swing.JMenuItem cursoMenuItem;
    private javax.swing.JPanel cursosTab;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem matricularAlunoItem;
    private javax.swing.JPanel tab;
    private javax.swing.JTable tabelaCursos;
    // End of variables declaration//GEN-END:variables

    private void hideAllDinamicMenus() {
        this.cursoMenu.setVisible(false);
    }
}
