/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deltamike.scoa.view.usuario;

import deltamike.scoa.controller.usuario.AlunoController;
import deltamike.scoa.controller.usuario.UsuarioController;
import deltamike.scoa.model.usuario.AlunoModel;
import deltamike.scoa.model.usuario.UsuarioModel;
import deltamike.scoa.view.Dashboard;
import deltamike.scoa.view.usuario.cadastrar.CadastrarAlunoForm;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodri
 */
public class UsuarioDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioDashboard
     */
    public UsuarioDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        UsuariosTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaUsuarios = new javax.swing.JTable();
        AtualizarUsuariosButton = new javax.swing.JButton();
        AlunosTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        AtualizarAlunosButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastrarAlunoItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "E-mail", "CPF", "telefone", "nome de usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaUsuarios);

        AtualizarUsuariosButton.setText("Atualizar");
        AtualizarUsuariosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarUsuariosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsuariosTabLayout = new javax.swing.GroupLayout(UsuariosTab);
        UsuariosTab.setLayout(UsuariosTabLayout);
        UsuariosTabLayout.setHorizontalGroup(
            UsuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
            .addGroup(UsuariosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AtualizarUsuariosButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsuariosTabLayout.setVerticalGroup(
            UsuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuariosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AtualizarUsuariosButton))
        );

        jTabbedPane1.addTab("Usuarios", UsuariosTab);

        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "E-mail", "id", "ano letivo", "carga horaria", "matricula", "situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaAlunos);

        AtualizarAlunosButton.setText("Atualizar");
        AtualizarAlunosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarAlunosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlunosTabLayout = new javax.swing.GroupLayout(AlunosTab);
        AlunosTab.setLayout(AlunosTabLayout);
        AlunosTabLayout.setHorizontalGroup(
            AlunosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlunosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(AlunosTabLayout.createSequentialGroup()
                .addComponent(AtualizarAlunosButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AlunosTabLayout.setVerticalGroup(
            AlunosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlunosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(AtualizarAlunosButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alunos", AlunosTab);

        jMenu1.setText("Cadastrar");

        CadastrarAlunoItem.setText("Aluno");
        CadastrarAlunoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAlunoItemActionPerformed(evt);
            }
        });
        jMenu1.add(CadastrarAlunoItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizarUsuariosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarUsuariosButtonActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) this.TabelaUsuarios.getModel();
        
        UsuarioController controller = (UsuarioController) Dashboard.springAppContext.getBean("usuarioController");
        
        List<UsuarioModel> usuarios = controller.getAll().getBody();
        
        model.setRowCount(0);
        
        
        //E-mail, CPF, telefone, username
        for(UsuarioModel usuario : usuarios){
            model.addRow(new Object[]{
                usuario.getId(),
                usuario.getCpf(),
                usuario.getTelefone(),
                usuario.getUsername()
            });
        }
    }//GEN-LAST:event_AtualizarUsuariosButtonActionPerformed

    private void CadastrarAlunoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAlunoItemActionPerformed
        // TODO add your handling code here:
        
        CadastrarAlunoForm cadastrarAlunoForm = new CadastrarAlunoForm();
        cadastrarAlunoForm.setVisible(true);
                
    }//GEN-LAST:event_CadastrarAlunoItemActionPerformed

    private void AtualizarAlunosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarAlunosButtonActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) this.tabelaAlunos.getModel();
        AlunoController controller = (AlunoController) Dashboard.springAppContext.getBean("alunoController");
        
        List<AlunoModel> alunos = controller.getAll().getBody();
        
        model.setRowCount(0);
        
        //E-mail, id, ano letivo, carga horaria, matricula, situação
        for(AlunoModel aluno : alunos){
            model.addRow(new Object[]{
                aluno.getUsuario() != null ? aluno.getUsuario().getId() : "",
                aluno.getId(),
                aluno.getAno_letivo(),
                aluno.getCarga_horaria(),
                aluno.getMatricula(),
                aluno.getSituacao()
            });
        }
        
    }//GEN-LAST:event_AtualizarAlunosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlunosTab;
    private javax.swing.JButton AtualizarAlunosButton;
    private javax.swing.JButton AtualizarUsuariosButton;
    private javax.swing.JMenuItem CadastrarAlunoItem;
    private javax.swing.JTable TabelaUsuarios;
    private javax.swing.JPanel UsuariosTab;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaAlunos;
    // End of variables declaration//GEN-END:variables
}
