/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deltamike.scoa.view.financeiro.cadastrar;

import deltamike.scoa.controller.financeiro.mensalidade.MensalidadeController;
import deltamike.scoa.controller.usuario.AlunoController;
import deltamike.scoa.controller.usuario.FuncionarioController;
import deltamike.scoa.controller.usuario.UsuarioController;
import deltamike.scoa.dtos.financeiro.mensalidade.MensalidadeDTO;
import deltamike.scoa.model.financeiro.mensalidade.MensalidadeModel;
import deltamike.scoa.model.usuario.AlunoModel;
import deltamike.scoa.model.usuario.FuncionarioModel;
import deltamike.scoa.model.usuario.UsuarioModel;
import deltamike.scoa.view.Dashboard;
import java.time.LocalDate;
import java.util.List;

/**
 *
 * @author rodri
 */
public class CadastrarMensalidadeFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarMensalidadeFrame
     */
    public CadastrarMensalidadeFrame() {
        initComponents();
        
        //populando combo box de alunos
        AlunoController alunoController = (AlunoController) Dashboard.springAppContext.getBean("alunoController");
        List<AlunoModel> alunos = alunoController.getAll().getBody();
        
        for(AlunoModel aluno : alunos){
            if(aluno.getUsuario() != null){
                this.alunoComboBox.addItem(aluno.getUsuario().getId());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        alunoComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        parcelaFixaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        parcelaVariavelTextField = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Aluno");

        jLabel2.setText("Parcela fixa (R$)");

        jLabel3.setText("Parcela variavel (R$/h)");

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alunoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 271, Short.MAX_VALUE))
                    .addComponent(parcelaFixaTextField)
                    .addComponent(parcelaVariavelTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cadastrarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alunoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parcelaFixaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parcelaVariavelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(cadastrarButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
        MensalidadeController mensalidadeController = (MensalidadeController) Dashboard.springAppContext.getBean("mensalidadeController");
        UsuarioController usuarioController = (UsuarioController) Dashboard.springAppContext.getBean("usuarioController");
        
        Integer parcelaFixa, parcelaVariavel;
        try {
            parcelaFixa = Integer.valueOf(this.parcelaFixaTextField.getText());
            parcelaVariavel = Integer.valueOf(this.parcelaVariavelTextField.getText());
        } catch (NumberFormatException e) {
            Dashboard.alert(e.toString());
            return;
        }
        
        LocalDate data = LocalDate.now();
        
        String aluno_email = this.alunoComboBox.getItemAt(this.alunoComboBox.getSelectedIndex());
        UsuarioModel usuario = (UsuarioModel) usuarioController.getById(aluno_email).getBody();
       
        
        MensalidadeDTO mensalidadeDTO = new MensalidadeDTO();
        mensalidadeDTO.setData(data);
        mensalidadeDTO.setParcela_fixa(parcelaFixa);
        mensalidadeDTO.setParcela_variavel(parcelaVariavel);
        mensalidadeDTO.setTotal(0);
        
        MensalidadeModel mensalidadeModel = (MensalidadeModel) mensalidadeController.save(mensalidadeDTO).getBody();
        mensalidadeController.colocarAlunoEmMensalidade(mensalidadeModel.getId(), usuario.getAluno().getId());        
        
        Dashboard.alert("Mensalidade cadastrada com sucesso!");
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarMensalidadeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarMensalidadeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarMensalidadeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarMensalidadeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarMensalidadeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alunoComboBox;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField parcelaFixaTextField;
    private javax.swing.JTextField parcelaVariavelTextField;
    // End of variables declaration//GEN-END:variables
}
