/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deltamike.scoa.view.financeiro.cadastrar;

import deltamike.scoa.controller.financeiro.folhadepagamento.FolhaDePagamentoController;
import deltamike.scoa.controller.usuario.FuncionarioController;
import deltamike.scoa.controller.usuario.UsuarioController;
import deltamike.scoa.dtos.financeiro.folhadepagamento.FolhaDePagamentoDTO;
import deltamike.scoa.model.financeiro.folhadepagamento.FolhaDePagamentoModel;
import deltamike.scoa.model.usuario.FuncionarioModel;
import deltamike.scoa.model.usuario.UsuarioModel;
import deltamike.scoa.util.StringToLocalDateConverter;
import deltamike.scoa.view.Dashboard;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author rodri
 */
public class CadastrarFolhaDePagamentoFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFolhaDePagamentoFrame
     */
    public CadastrarFolhaDePagamentoFrame() {
        initComponents();
        
        //populando combo box de funcionarios
        FuncionarioController funcionarioController = (FuncionarioController) Dashboard.springAppContext.getBean("funcionarioController");
        List<FuncionarioModel> funcionarios = funcionarioController.getAll().getBody();
        
        for(FuncionarioModel funcionario : funcionarios){
            if(funcionario.getUsuario() != null){
                this.funcionarioComboBox.addItem(funcionario.getUsuario().getId());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        funcionarioComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        pagamentoLiquidoSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        pagamentoBrutoSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        dataTextField = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Colaborador");

        jLabel2.setText("Pagamento liquido");

        jLabel3.setText("Pagamento bruto");

        jLabel4.setText("Data");

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pagamentoBrutoSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(funcionarioComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 287, Short.MAX_VALUE))
                    .addComponent(pagamentoLiquidoSpinner)
                    .addComponent(dataTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cadastrarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funcionarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagamentoLiquidoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagamentoBrutoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(cadastrarButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
        FolhaDePagamentoController folhaDePagamentoController = (FolhaDePagamentoController) Dashboard.springAppContext.getBean("folhaDePagamentoController");
        UsuarioController usuarioController = (UsuarioController) Dashboard.springAppContext.getBean("usuarioController");
        
        String funcionarioEmail = this.funcionarioComboBox.getItemAt(this.funcionarioComboBox.getSelectedIndex());
        UsuarioModel usuario = (UsuarioModel) usuarioController.getById(funcionarioEmail).getBody();
        FuncionarioModel funcionario = usuario.getFuncionario();
        
        //confirmando alterações manuais nos spinners de pagamento
        try {
            this.pagamentoBrutoSpinner.commitEdit();
            this.pagamentoLiquidoSpinner.commitEdit();
        } catch (ParseException e) {
            Dashboard.alert(e.toString());
            return;
        }
        
        //validando data de pagamento
        LocalDate data;
        try {
            data = StringToLocalDateConverter.convert(this.dataTextField.getText());
        } catch (Exception e) {
            Dashboard.alert(e.toString());
            return;
        }
        
        FolhaDePagamentoDTO folhaDePagamentoDTO = new FolhaDePagamentoDTO();
        folhaDePagamentoDTO.setData(data);
        
        Integer bruto = (Integer)this.pagamentoBrutoSpinner.getValue();
        Integer liquido = (Integer)this.pagamentoLiquidoSpinner.getValue();
        
        folhaDePagamentoDTO.setPagamento_bruto(bruto.floatValue());
        folhaDePagamentoDTO.setPagamento_liquido(liquido.floatValue());
        
        FolhaDePagamentoModel pagamentoModel = (FolhaDePagamentoModel) folhaDePagamentoController.save(folhaDePagamentoDTO).getBody();
        folhaDePagamentoController.colocarFuncionarioEmFolhaDePagamento(pagamentoModel.getId(), funcionario.getId());
        Dashboard.alert("Pagamento cadastrado com sucesso");
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFolhaDePagamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFolhaDePagamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFolhaDePagamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFolhaDePagamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFolhaDePagamentoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField dataTextField;
    private javax.swing.JComboBox<String> funcionarioComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner pagamentoBrutoSpinner;
    private javax.swing.JSpinner pagamentoLiquidoSpinner;
    // End of variables declaration//GEN-END:variables
}
