-- MySQL Script generated by MySQL Workbench
-- Fri Sep 30 08:24:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Scoa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Scoa` DEFAULT CHARACTER SET utf8 ;
USE `Scoa` ;

-- -----------------------------------------------------
-- Table `Scoa`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scoa`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Scoa`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `tipo` BIT NOT NULL,
  `data_Cadastro` DATETIME NOT NULL,
  `data_Alteracao` DATETIME NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `inativo` BIT NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `ano` YEAR NOT NULL,
  `serie` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Id_UNIQUE` (`idUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scoa`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scoa`.`Curso` ;

CREATE TABLE IF NOT EXISTS `Scoa`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_Cadastro` DATETIME NOT NULL,
  `data_Alteracao` DATETIME NOT NULL,
  `inativo` BIT NOT NULL,
  `cadastrado_por_usuario_id` INT NOT NULL,
  `curso_serie` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  UNIQUE INDEX `idCurso_UNIQUE` (`idCurso` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scoa`.`Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scoa`.`Disciplina` ;

CREATE TABLE IF NOT EXISTS `Scoa`.`Disciplina` (
  `idDiciplina` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `curso_id` INT NOT NULL,
  `data_Cadastro` VARCHAR(45) NOT NULL,
  `data_Alteracao` VARCHAR(45) NOT NULL,
  `cadastrado_por_usuario_id` INT NOT NULL,
  `inativo` BIT NOT NULL,
  PRIMARY KEY (`idDiciplina`),
  INDEX `idCurso_idx` (`curso_id` ASC) VISIBLE,
  UNIQUE INDEX `idDiciplina_UNIQUE` (`idDiciplina` ASC) VISIBLE,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`curso_id`)
    REFERENCES `Scoa`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scoa`.`Turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scoa`.`Turma` ;

CREATE TABLE IF NOT EXISTS `Scoa`.`Turma` (
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_Cadastro` DATETIME NOT NULL,
  `data_Alteracao` DATETIME NOT NULL,
  `cadastrado_por_usuario_id` INT NOT NULL,
  `turno` TIME NOT NULL,
  `curso_id` INT NOT NULL,
  `ano` YEAR NOT NULL,
  `inativo` BIT NOT NULL,
  PRIMARY KEY (`idTurma`),
  UNIQUE INDEX `idTurma_UNIQUE` (`idTurma` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scoa`.`Sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scoa`.`Sala` ;

CREATE TABLE IF NOT EXISTS `Scoa`.`Sala` (
  `idSala` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `data_alteracao` DATETIME NOT NULL,
  `cadastrada_usuario_id` INT NOT NULL,
  `inativo` BIT NOT NULL,
  `cadastrado_por_usuario_id` INT NOT NULL,
  PRIMARY KEY (`idSala`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scoa`.`Turma_Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scoa`.`Turma_Disciplina` ;

CREATE TABLE IF NOT EXISTS `Scoa`.`Turma_Disciplina` (
  `idTurma_Disciplina` INT NOT NULL AUTO_INCREMENT,
  `turma_id` INT NOT NULL,
  `diciplina_id` INT NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `sala_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `cadastrado_por_usuario_id` INT NOT NULL,
  `horario_termino` TIME NOT NULL,
  PRIMARY KEY (`idTurma_Disciplina`),
  UNIQUE INDEX `idDisciplina_Turma_UNIQUE` (`idTurma_Disciplina` ASC) VISIBLE,
  INDEX `turma_idx` (`turma_id` ASC) VISIBLE,
  INDEX `disciplina_idx` (`diciplina_id` ASC) VISIBLE,
  INDEX `sala_idx` (`sala_id` ASC) VISIBLE,
  INDEX `professor_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `turma`
    FOREIGN KEY (`turma_id`)
    REFERENCES `Scoa`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disciplina`
    FOREIGN KEY (`diciplina_id`)
    REFERENCES `Scoa`.`Disciplina` (`idDiciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sala`
    FOREIGN KEY (`sala_id`)
    REFERENCES `Scoa`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `professor`
    FOREIGN KEY (`professor_id`)
    REFERENCES `Scoa`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scoa`.`Aluno_Turma_Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scoa`.`Aluno_Turma_Disciplina` ;

CREATE TABLE IF NOT EXISTS `Scoa`.`Aluno_Turma_Disciplina` (
  `idAluno_Turma_Disciplina` INT NOT NULL AUTO_INCREMENT,
  `turma_disciplina_id` INT NOT NULL,
  `aluno_id` INT NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `data_alteracao` DATETIME NOT NULL,
  `ultima_alteracao_usuario_id` INT NOT NULL,
  `p1` DOUBLE NOT NULL,
  `p2` DOUBLE NOT NULL,
  `p3` DOUBLE NOT NULL,
  `cadastrado_por_usuario_id` INT NOT NULL,
  `inativo` BIT NOT NULL,
  PRIMARY KEY (`idAluno_Turma_Disciplina`),
  INDEX `turma_disciplina_idx` (`turma_disciplina_id` ASC) VISIBLE,
  INDEX `aluno_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `turma_disciplina`
    FOREIGN KEY (`turma_disciplina_id`)
    REFERENCES `Scoa`.`Turma_Disciplina` (`idTurma_Disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aluno`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `Scoa`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
