-- MySQL Script generated by MySQL Workbench
-- Thu Sep 29 21:32:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Scoa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Scoa` DEFAULT CHARACTER SET utf8 ;
USE `Scoa` ;

-- -----------------------------------------------------
-- Table `Scoa`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Scoa`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Data_Cadastro` DATETIME NOT NULL,
  `Data_Alteracao` DATETIME NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scoa`.`Obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Scoa`.`Obra` (
  `idObra` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL,
  `Ano_Publicacao` DATE NULL,
  `Idioma` VARCHAR(45) NULL,
  `Palavras_Chave` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Autor` VARCHAR(45) NULL,
  `Quantidade_Paginas` INT NULL,
  `Assunto` VARCHAR(45) NULL,
  `Sinopse` VARCHAR(45) NULL,
  `ISBN` VARCHAR(45) NULL,
  `Editora` VARCHAR(45) NULL,
  `Manchete` VARCHAR(45) NULL,
  `Diretores` VARCHAR(45) NULL,
  `Distribuidor` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Duracao` TIME NULL,
  PRIMARY KEY (`idObra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scoa`.`Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Scoa`.`Emprestimo` (
  `idEmprestimo` INT NOT NULL AUTO_INCREMENT,
  `Obras` INT NULL,
  `Cliente` INT NULL,
  `Prazo` DATETIME NULL,
  `Data_Registro` DATETIME NULL,
  PRIMARY KEY (`idEmprestimo`),
  INDEX `Obra_idx` (`Obras` ASC) VISIBLE,
  INDEX `Cliente_idx` (`Cliente` ASC) VISIBLE,
  CONSTRAINT `Obra`
    FOREIGN KEY (`Obras`)
    REFERENCES `Scoa`.`Obra` (`idObra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cliente`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Scoa`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
